### ISSUE TITLE
The downloadable Arc COLORA themes don't support GTK 3.20+

### ISSUE THREAD

**Issue by luisfpg** [erikdubois/Arc-Theme-Colora#1]
On Arch Linux all themes look bad, because they don't support GTK 3.20.
The official Arc theme does support GTK 3.20+, so maybe it is just a rebase.

**Comment by erikdubois** [comment]
Ofcourse I tried that too... they have been made for LINUX MINT 18 ON LINUX MINT. 
When you are on SOLUS you should make them on SOLUS. See github Ultimate Solus
When you are on ARCH you should make them on ARCH.
We all like a good copy/paste but unfortunately....
