### ISSUE TITLE
Invalid GNOME version (Update upstream?)

### ISSUE THREAD

**Issue by SuperPrower** [erikdubois/Arc-Theme-Colora#15]
It seems tat `NicoHood/arc-theme` is a new upstream for arc theme. I tried manually changing url in installation1 script, but it seems like directory structure has changed, because I get errors about non-existing path that I didn't get when I was running raw script. 

Without changing git url, when building theme, I get error saying that `Invalid GNOME version: 3.24` is incorrect. I saw similar error in 'new upstream', so I suspect that this has to do with Arc Theme version.

**Comment by erikdubois** [comment]
indeed not going to be easy

**Comment by spalmesano0** [comment]
Looks like that upstream may be working on something: https://github.com/NicoHood/arc-theme/blob/master/change_color.sh

I couldn't get the script to work and it doesn't seem like there's any documentation on it.

**Comment by erikdubois** [comment]
who knows
