### ISSUE TITLE
Why not one script?

### ISSUE THREAD

**Issue by kcpr** [erikdubois/Arc-Theme-Colora#16]
Hi,
first of all - thank You for Your work. It works brilliantly! To be honest though I had some trouble at first as I wasn't aware that I have to manually edit the second script. That all makes me a bit curious: why not have just one script which does everything? 'Yes/No' questions and at least one asking about the color would be probably a necessity, but I believe it would be a way more user-friendly. What do You think? Or maybe it was Your plan from the beginning but it's just a matter of time?
Thanks a lot again!

**Comment by erikdubois** [comment]
my first day of scripting
you learn as you go
