### ISSUE TITLE
Old Arc colors ending up in ~/.themes

### ISSUE THREAD

**Issue by mikeldavis** [erikdubois/Arc-Theme-Colora#18]
After running all the scripts in order on MX Linux, changing the color in the 2nd script to a purple before running, themes with the Arc-$choice name were all in the ~/.themes folder as expected, but the files all still had the old blue Arc theme color and assets were the old blue ones. ~/Arc-Theme-Colora/arc-theme/common had the assets with the new purple color. I don't understand which script did not complete successfully and just copied and pasted from one place to the other to get my new purple theme, but wanted to report it hoping someone who knows more could help improve the scripts to work with MX Linux.

**Comment by erikdubois** [comment]
These scripts need to be revised.
Arc has changed from owner... 
Do not know if that has anything to do with it
It is on my to do list - just not a high priority
