### ISSUE TITLE
Cinnamon 3.2 with Arc themes - calendar unreadable

### ISSUE THREAD

**Issue by geckolinux** [erikdubois/Arc-Theme-Colora#2]
Hi, first of all I'd like to say that Arc Theme Colora is a fantastic project that I use on my main systems. Thanks very much for the excellent themes!

A new issue has come up with the upgrade to Cinnamon 3.2. Now, the calendar is almost unreadable. The rest of the theme still works well.

![screenshot from 2016-11-14 10-09-38](https://cloud.githubusercontent.com/assets/2692138/20269843/db92b2d6-aa52-11e6-9993-f871eb23174d.png)

Thanks, and best regards.

**Comment by erikdubois** [comment]
not yet on this version...
How did you update to this version so I can do the same?
thanks
Erik

2016-11-14 16:13 GMT+01:00 geckolinux notifications@github.com:

**Comment by erikdubois** [comment]
installed 3.2.1 already

2016-11-16 18:21 GMT+01:00 Erik Dubois erik.dubois@gmail.com:

**Comment by erikdubois** [comment]
2016-11-16 18:41 GMT+01:00 Erik Dubois erik.dubois@gmail.com:

**Comment by erikdubois** [comment]
here everything looks good.
But these are the old files.
Did you run the scripts on the cinnamon 3.2 and then encounter the problem.
What theme is that arc dark sun? Because that looks ok.

2016-11-16 18:47 GMT+01:00 Erik Dubois erik.dubois@gmail.com:

**Comment by geckolinux** [comment]
Hi, thanks for the reply.

I didn't run the scripts, I just downloaded the current Arc-Theme-Colora 
master branch. Yes, it's Arc Sun. The problem is that the calendar 
numbers are invisible.

Thanks for the help!

**Comment by erikdubois** [comment]
everything looks good under Linux Mint 18 Cinnamon 
made a Arc Violet theme today and calender looks good.
![calendar](https://cloud.githubusercontent.com/assets/10594806/20476819/2f9a6358-afd3-11e6-905e-7e7698a14d30.jpg)
Maybe running the scripts again might help you out.

**Comment by geckolinux** [comment]
Hi @erikdubois , the difference with my system is that I am on Cinnamon 3.2 with GTK 3.22. I believe that Mint 18 has Cinnamon 3.0 with GTK 3.20.

I have been using Arc-Theme-Colora for many months, and this problem only appeared when upgrading to Cinnamon 3.2.

**Comment by erikdubois** [comment]
Aha not linux mint?
Arch
I need to know what distro you are on
Op ma 21 nov. 2016 om 12:13 schreef geckolinux notifications@github.com

**Comment by geckolinux** [comment]
openSUSE Tumbleweed.

**Comment by erikdubois** [comment]
Everything looks fine on my end as you can see in my screenshot.
Suse tumbleweed
cinnamon version 3.2.1
gtk3.22.3
I ran the scripts 0-1-2-3 on plasma and downloaded/installed in the meantime cinnamon. Switched to cinnamon and run script 4 there. Stopped there and selected Arc dark.

Retrace your own steps to see if you can find a solution.

BUT you should definitely run the scripts if not on linux mint 18. 

![2016-11-23-104935_3600x1080_scrot](https://cloud.githubusercontent.com/assets/10594806/20557207/dff10e1c-b16a-11e6-9e7c-5e5ec2d19bf4.png)

**Comment by outhud** [comment]
@erikdubois which font are you using in those screenshots? Looks great.

**Comment by erikdubois** [comment]
no way of knowing anymore - has been formatted - screenfetch says  "sans 9"
