### ISSUE TITLE
Color didn't change at some places

### ISSUE THREAD

**Issue by i3wm** [erikdubois/Arc-Theme-Colora#4]
My system:- Arch Linux (i686)

I ran the scripts from 0 to 4 to change the color of the theme. The color was applied to most of the places except for the context menu of menu bar of all applications such as Thunar, GVim, etc.

A screenshot of the issue:- [Thunar](http://imgur.com/Obn3my5)

**Comment by erikdubois** [comment]
thanks for reporting

**Comment by i3wm** [comment]
@erikdubois Solved the problem. After a little digging found out that the problem occurs only with the dark variant of the theme i.e., `Arc-Dark` and not with `Arc` or `Arc-Darker`. There seems to be a problem during the installation of theme to `/usr/share/themes/` using script number 4. Instead of all the png files that should be present in `/usr/share/themes/Arc-Dark/gtk-2.0/assets/`, it contains another folder `/usr/share/themes/Arc-Dark/gtk-2.0/assets/assets-dark/` which in turn contains all the png files. As such the theme was not rendered correctly, 

So, this command solved the issue:-

> sudo cp -r /usr/share/themes/Arc-Dark/gtk-2.0/assets/assets-dark/* /usr/share/themes/Arc-Dark/gtk-2.0/assets/ && sudo rm -rf /usr/share/themes/Arc-Dark/gtk-2.0/assets/assets-dark

You might want to edit your script number 4 to fix the issue.

Thank you.

**Comment by erikdubois** [comment]
thanks for getting back to me
it is on my to do list
love the arc theme

**Comment by erikdubois** [comment]
You found the problem. Spot on. Sadly the issue comes in step 4. Meaning it is the installation process of Arc itself were the problem is. I will report the issue in due time on their github. It is always quite difficult to explain what goes wrong and where.

**Comment by erikdubois** [comment]
Made Arc Smoke and Arc Luv. 
Still not sure where the problem is. I assume it is with me. Found one error trying to figure out the issue. 
Added your line for the moment as a fix.

**Comment by i3wm** [comment]
@erikdubois Thank you for fixing it. In the mean time, I too will try to find out a better solution.
