### ISSUE TITLE
Unchanged buttons color (GTK/Gnome)

### ISSUE THREAD

**Issue by GitSquared** [erikdubois/Arc-Theme-Colora#5]
![screenshot from 2017-01-22 15-11-20](https://cloud.githubusercontent.com/assets/24496417/22183064/0fa507f2-e0b5-11e6-91fa-27e6d4db5ced.png)

These buttons, found for example on the file chooser window, aren't modified with the color changer script (first one I think).

I digged a bit in gtk.css and found these color codes:

* #4DADD4 - Default button color, blue
* #76c0de - Hover button color, lighter blue (This hex code was not capitalized by Colora's script, is this an error?)
* #2e96c00 - Suggested action button, darker blue (Not capitalized too)

Hope it helps!

**Comment by erikdubois** [comment]
thanks will check it - which distro and how can i recreate this issue

Op zo 22 jan. 2017 om 15:13 schreef Git² <notifications@github.com>:

**Comment by GitSquared** [comment]
Happened on Arch Linux w/ Gnome, steps to reproduce:

- Make a colored theme
- Install it
- Open a file chooser window (or go to gnome-tweak-tool extensions page and activate some)
- Blue buttons everywhere

**Comment by erikdubois** [comment]
i think I fixed the last blue colours... I think
can you check and get back in touch before I close this issue?

**Comment by GitSquared** [comment]
Will do some testing tomorrow morning. I'll post the results here.

**Comment by GitSquared** [comment]
The buttons no longer bright up when hovered, but this would be tricky to do and the issue has been fixed anyway. Thanks!
