### ISSUE TITLE
More Intuitive naming theme variants.

### ISSUE THREAD

**Issue by AnwarShah** [erikdubois/Arc-Theme-Colora#6]
Currently the naming script names the 3 theme variants by appending the chosen name at the end of the `Arc`, `Arc-Dark`, `Arc-Darker`. For example, for a name `Teal`, it generates themes names `Arc-Teal`, `Arc-Dark-Teal`, `Arc-Darker-Teal` which are confusing when you install several of the customized one.

I propose to name it by adding the `Teal` or chosen name just after the `Arc` word. So, it will become like `Arc-Teal`, `Arc-Teal-Dark`, `Arc-Teal-Darker` which are more intuitive and easy to understand names.

**Comment by erikdubois** [comment]
was easiest for the renaming script
if you can provide a solution would be great.
[link to script](https://github.com/erikdubois/Arc-Theme-Colora/blob/master/5-moving-and-renaming-the-themes.sh)
and push it back 
swamped with new project [Archlabs](https://archlabsblog.wordpress.com/)

**Comment by AnwarShah** [comment]
Ok, I'd be creating a PR then.

**Comment by AnwarShah** [comment]
@erikdubois I've created a PR. You can merge. I've also updated README a bit, but didn't include it in this PR thinking you might want to update it yourself.

**Comment by erikdubois** [comment]
i have used your script and it will work as you suggested now.
thanks for the helping hand
in the meantime it will also support openbox with file 8-openbox-themerc
