### ISSUE TITLE
If a user already have original Arc theme installed, backup them

### ISSUE THREAD

**Issue by AnwarShah** [erikdubois/Arc-Theme-Colora#7]
It would be nice if you don't need to have Arc re-built if you already had the theme installed. I suggest backing up the original theme if it exists somewhere. Then if a user wants to restore the original theme, just restore the backup.

Building takes time and active internet connection, which may not be available sometimes and it is easier anyway.

**Comment by erikdubois** [comment]
I kept this one in. I want them to have the latest of the net. I want to have the latest of the net.
